<template>
  <font-awesome-icon :icon="name" v-bind="$attrs" :class="['icon', styleClasses]" />
</template>
<script>
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowRight,
  faAngleRight,
  faAngleDown,
  faPenToSquare,
  faAward,
  faBox,
  faBoxOpen,
  faBuilding,
  faBullhorn,
  faCalendarDays,
  faCartPlus,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleNotch,
  faDollarSign,
  faDownload,
  faEdit,
  faEllipsis,
  faEnvelopeOpenText,
  faEye,
  faFileExport,
  faGear,
  faGift,
  faGifts,
  faHandHoldingUsd,
  faHome,
  faIdCard,
  faImages,
  faInbox,
  faLayerGroup,
  faListAlt,
  faLuggageCart,
  faMapLocationDot,
  faPen,
  faPhotoVideo,
  faPlus,
  faMinus,
  faPrint,
  faQuestionCircle,
  faRotateRight,
  faRulerCombined,
  faShoppingBasket,
  faShoppingCart,
  faSitemap,
  faStore,
  faSwatchbook,
  faTags,
  faTrashAlt,
  faTruck,
  faTruckFast,
  faUser,
  faUserCheck,
  faUserCog,
  faUserFriends,
  faUsers,
  faUsersCog,
  faXmark,
  faSpinner,
  faPencil,
  faBold,
  faItalic,
  faUnderline,
  faStrikethrough,
  faAlignLeft,
  faAlignRight,
  faAlignCenter,
  faAlignJustify,
  faListUl,
  faListOl,
  faSubscript,
  faSuperscript,
  faCode,
  faRotateLeft,
  faTable,
  faCircleDot,
  faCircleExclamation,
  faLink,
  faFaceSmile,
  faFaceFrown,
  faThumbTack,
  faClipboardList,
  faListCheck,
  faRightFromBracket,
  faFileLines,
  faArrowDown,
  faFileArrowDown,
  faQuoteLeft,
  faUserShield,
  faBookmark,
  faCodePullRequest,
  faFolderTree,
  faTrophy,
  faFilter,
  faArrowUpWideShort,
  faArrowDownWideShort,
  faRocket,
  faTag,
  faCalendar
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

library.add(
  // faHome,
  // faBox,
  // faBoxOpen,
  // faLuggageCart,
  // faShoppingCart,
  faUsers,
  // faHandHoldingUsd,
  // faLayerGroup,
  // faIdCard,
  // faChartLine,
  // faDollarSign,
  // faEnvelopeOpenText,
  // faStore,
  // faUserCog,
  // faInbox,
  // faAward,
  // faUserCheck,
  // faUserFriends,
  // faQuestionCircle,
  // faUsersCog,
  // faSwatchbook,
  faListAlt,
  // faTruckFast,
  // faPhotoVideo,
  // faSitemap,
  // faEdit,
  // faEye,
  faUser,
  faTrashAlt,
  faImages,
  // faShoppingBasket,
  // faGift,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  // faCircleNotch,
  // faFileExport,
  faCheck,
  faXmark,
  // faBuilding,
  faDownload,
  faArrowRight,
  faAngleRight,
  faAngleDown,
  faPenToSquare,
  faRotateRight,
  // faRulerCombined,
  faGear,
  // faMapLocationDot,
  // faPrint,
  // faPen,
  // faTags,
  faCalendarDays,
  // faGifts,
  // faPlus,
  // faMinus,
  // faBullhorn,
  // faCartPlus,
  // faEllipsis,
  faTruck,
  faSpinner,
  faPencil,
  faBold,
  faItalic,
  faUnderline,
  faStrikethrough,
  faAlignLeft,
  faAlignRight,
  faAlignCenter,
  faAlignJustify,
  faListUl,
  faListOl,
  faSubscript,
  faSuperscript,
  faCode,
  faRotateLeft,
  faTable,
  faCircleDot,
  faCircleExclamation,
  faLink,
  faFaceSmile,
  faFaceFrown,
  faThumbTack,
  faClipboardList,
  faListCheck,
  faRightFromBracket,
  faHome,
  faFileLines,
  faFileArrowDown,
  faQuoteLeft,
  faUserShield,
  faBookmark,
  faCodePullRequest,
  faFolderTree,
  faTrophy,
  faFilter,
  faTable,
  faArrowUpWideShort,
  faArrowDownWideShort,
  faRocket,
  faTag,
  faCalendar
);

export default {
  name: 'AppIcon',
  components: {
    FontAwesomeIcon
  },
  inheritAttrs: false,
  props: {
    name: {
      type: String,
      default: 'default'
    },
    size: {
      type: String,
      default: ''
    },
    color: {
      type: String,
      default: ''
    }
  },
  computed: {
    path() {
      return icons[this.name];
    },
    styleClasses() {
      return [this.size, this.color].map((val) => val && `is-${val}`);
    }
  }
};
</script>
