<?php

$isLive = env('IS_LIVE');
$repositories = [
    'ecommerce-spa',
    'vox-ecommerce-spa',
    'srpl-plus-front-end',
    'srpl-plus-adminportal',
    'process-documentation-cms',
    'ecommerce-saas-api',
    'srpl-plus-api',
    'vox-ecommerce-sso',
    'ecommerce-saas-lambdas',
    'ecommerce-superadmin',
    'voxships-api',
    'voxships-warehouse-app',
    'voxships-thirdparty',
    'voxships-lambda-files',
    'voxships-accounting',
    'vox-snkrs-backend',
    'customer-appreciation',
    'aws-ses-email-templates',
    'ecommerce-notifications-ses',
    'showroom-app',
    'st_promotion_catalogs',
    'showroom-customer-app',
    'vivint-stores-lambdas',
    'ecommerce-wegift',
    'ShowRoomApp-lambda',
    'amazon_business_app',
    'vox-ecommerce-supportportal',
    'voxships-clientportal',
    'api-haulin-aggs',
    'srpl-lambdas-filesSRPL-lambda',
    'vivint-store-v2',
    'DropApp-lambda',
    'rpm-living-customer-appreciation',
    'app-haulin-aggs',
    'ecommerce-sts',
    'hormone-balance-patient-portal',
    'hormone-balance-portal',
    'admin-haulin-aggs',
    'vivint-prize-locker',
    'shipment-tracking',
    'entrata',
    'close-contact',
    'sunrun-customer-gifts',
    'swag-drop-app',
    'vox-ecommerce-notification-engine',
    'TDMS-mobile',
    'mikes-crm-backend',
    'summer-sales',
    'ecommerce-mobile-app',
    'shikhartechsite',
    'showroom_app_public',
    'voxships-logs-backup',
    'xtra',
    'ecommerce_accounting',
    'lambda-one-click-billing',
    'sunrun-aws-v2',
    'shikhartech-site',
    'fox_pest',
    'teamexos-v2',
];
$env_repositories = json_decode(env('GITHUB_REPOSITORY', '[]'));

return [
    'owner' => $isLive ? 'shikhartech' : env('GITHUB_USER_NAME'),
    'repository' => $isLive ? $repositories : $env_repositories,
    'base' => $isLive ? 'main' : env('GITHUB_BASE_BRANCH'),
    'head' => $isLive ? 'production' : env('GITHUB_HEAD_BRANCH'),
    'accessToken' => env('GITHUB_ACCESS_TOKEN'),
];
